### ISSUE TITLE
The 'option' parameter in data_objects/{connection_id} is a bit weirdly named. 

### ISSUE THREAD

**Issue by Stroomversnelling** [Stroomversnelling/monitoring_api#12]
**Is your feature request related to a problem? Please describe.**
The 'option' parameter in data_objects/{connection_id} is a bit weirdly named. 

**Describe the solution you'd like**
Give it a more descriptive name.

**Comment by nickdickinson** [comment]
Suggest 'time_period' to replace both resolution and option with the following options:
- an integer value for the number of minutes in a period (1 - 60)
- "day"
- "week"
- "month"
- "year"

**Comment by rsa2010** [comment]
Not preferred since the option represents a set of aggregation functions. 
The resolution allows you to extract raw values from the database at a certain resolution (if available, else it should return the closest resolution available).

**Comment by FilipAben** [comment]
How useful is it to extract raw values at a certain resolution? Consider the following:
When logging values, it is hard to guarantee that resolution of raw values match up exactly to the second. They could be subject to sampling delays, outages, which can cause them to skew the targeted resolution. Therefore, if it is required to return consistent resolutions, there's always an amount of post-processing involved by interpolating values at certain timestamps. This makes it non-raw data instead of raw data. But thinking further, this makes it identical to requesting an aggregation of the intended resolution. So there's little point in having it. Though it might be useful to have a 'raw' aggregation option which just returns the data as-logged, without any processing.

Additionally, picking raw values at different resolutions doesn't make sense for a lot of measurements which are specified in appendix A.3 of the specification. It is especially confusing for kwh/interval type of measurements

**Comment by rsa2010** [comment]
It all depends on how you have your database and sample points organized. The API does not dictate how you should store and/or process. The specification gives you a maximal interval between datapoints (mostly at least once every hour but it does not dictate that measurements from different objects are in any way aligned). The response data should include the timestamp and the distance between timestamps should be greater than what is requested in the specification. resolution could be renamed to minimal interval (or requested interval) if that makes it clearer (I think it does).  

Dropping it all together may not be in the interest of all parties that participated in developping the API (some may have higher resolution data and may not have skew issues)

**Comment by FilipAben** [comment]
I know the API doesn't dictate that, I'm merely illustrating a potential problem with implementing it as it was defined. 'minimal interval' is a different thing than 'resolution'. 
It also submits the resulting dataset to the whim of the data provider & thus more unpredictable to the data requester. I think these things should be avoided when making an API which aims to standardize data exchange between different stakeholders.

I'm curious: which are the use cases that motivated including a 'resolution/minimal interval' option for raw data ? Cases that are not covered by the aggregation option.

Final note: how would 'resolution/minimal interval' work together with the 'aggregation' option? I think it should be one or the other, not both?

**Comment by nickdickinson** [comment]
Can we use a time_interval as a replacement for both option and resolution to specify the desired time interval by the requester? If they want raw values instead of aggregated values, then it seems to me that this should be a switch rather than based on whether option or resolution is specified.

**Comment by FilipAben** [comment]
Yes, indeed

**Comment by Stroomversnelling** [comment]
Fixed.
