### ISSUE TITLE
timezones & delta_day, delta_week, delta_month values

### ISSUE THREAD

**Issue by FilipAben** [Stroomversnelling/monitoring_api#16]
start_time & end_time are specified in UTC time, which renders it timezone-agnostic. 
But the delta_day, delta_week, delta_month values of the 'option' parameter cannot be timezone-agnostic, since that would yield results which are not very useful and accurate to us poor souls living in UTC+1 or UTC+2 depending on daylight savings. 
I assume the implicit timezone is currently "europe/amsterdam", but this not made explicit anywhere.
Also, if the stroomversnelling standard would be carried beyond the Netherlands, it would need to be configurable.

**Comment by nickdickinson** [comment]
Agreed, how would we configure this? At what level? For the whole API should we be using the full dates with timezone specified?

**Comment by rsa2010** [comment]
Timezone is part of the profile and response data is in the format timestamp (Unix epoch), value
So changing timezone only needs to be done for the UI.
The request start and end_time are currently in ISO8601 (for testing purposes but better to also specify this in UNIX epoch

**Comment by FilipAben** [comment]
> So changing timezone only needs to be done for the UI.

I'm not sure I follow. If you're saying that only the UI needs to be aware of the timezone, then that is not true. If you're using day, week or month aggregations, the backend needs to be timezone-aware in order to return correct data.

**Comment by rsa2010** [comment]
It is up to you how you structure your backend for timezone details to do aggregation.
The only thing the API states is how the UI will be made aware of this timezone (you can not set a timezone through the API, the API just informs the data consumer of the timezone being used through the profile).
Aggregation is up to the PDB supplier. Weekstart could also be on a monday or on a sunday and if using week numbers we may start week 1 at first full week of januari etc...if the full epoch timestamp is included the UI could identify which is used. We would need to specify the timestamp to be at the start of the end of the aggregation period, (I opt for end) or if aggregation should give weeknumbers (isoweeks).
So that would be a point of discussion

**Comment by nickdickinson** [comment]
It makes a lot of sense to allow the norm to address how aggregation should be done by monitoring providers and just ensuring that whatever the standard is that is used by the monitoring norm and/or by the monitoring providers, the API is able to provide that information in a well specified format without ambiguity. 

Let's say you put time stamp at as the last second of January and your period is a month, the tricky thing however is this could be different months in different timezones and even if it is the end of the timeperiod and means that additional logic would be needed to avoid ambiguous results. Also note each month has a different length so a delta_month is a tricky thing anyway.

Shouldn't we be providing the start and end timestamp in these cases to avoid all ambiguity?

If it is a cumulative value, clearly it won't matter. If it is a value (avg, sum) over a range then it does.

**Comment by FilipAben** [comment]
Providing start & end timestamp is an option but it also implies that, since we can't make assumptions about start & end timestamp neatly aligning on day, month...,  a PDB supplier is forced to calculate aggregations on the fly from raw data instead of pre-calculating them.

**Comment by Stroomversnelling** [comment]
Fixed.
