### ISSUE TITLE
Add endpoint to request all data errors

### ISSUE THREAD

**Issue by Stroomversnelling** [Stroomversnelling/monitoring_api#3]
**Is your feature request related to a problem? Please describe.**
Appendix E (Data Quality) of the Monitoring Norm require being able to check for data errors. 

**Describe the solution you'd like**
A separate endpoint to query a list of errors. 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nickdickinson** [comment]
The agreement was to first specify error data as part of a queried data object within a time range. This should allow an app to query errors. The point of this is that errors are time- and variable dependent. Something that might be an error during a query made on January 20th 2019 might have been resolved by the time you are looking of the data for the entire year of 2019 and thus not show up anymore. 

Currently the API has not implemented these error fields and these will be added but within existing end points for data objects. If you think a separate end point is still needed, then please explain.

**Comment by FilipAben** [comment]
I'm interested to see how it would be implemented. Would it be returned as integral part of the time series? If so, should that change when aggregations are requested?

There's also mention of data errors in #4 . If you would regard the log endpoint as providing annotations to the data of a data_object, it might even make sense to return all logs that apply to a data_object when it is queried, and not just the data errors. Or not return these logs when querying data but implement the log endpoint such that you can do {connection_id}/log?data_object=xxxxx and get all annotations.

**Comment by rsa2010** [comment]
It was discussed that it should only show errors involved in the required aggregation. 
For instance if you would do a delta month for E_dom (based on kwh readings from end of the month minus kwh readings from start of the month), there is no need to show a delta error that occured somewhere mid month (since there is no relevance to this error in the required aggregation function as long as readings at start and end are valid).
But if you have a missing datapoint at month start or month end you should report this (including the timestamp on where the error occured.
The log data is included in the response data (I see it is not yet in the API YAML).

```data_objects response
[
  {
    "data_object": {
      "object_id": 0,
      "name": "string",
      "description": "string",
      "unit": "string",
      "granularity": 0,
      "quality": "string",
      "members": [
        "string"
      ],
      "operations": [
        "string"
      ]
    },
    "time_series": [
      {
        "timestamp": 0,
        "value": 0
      }
    ]
    "anomalies": [
      {
        "timestamp": 0,
        "error": 0
      }
    ]
  }
]
```

**Comment by Stroomversnelling** [comment]
Fixed.
